/* Tests run against synthetic in-memory contacts, never the user's browser data. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../app.html'),'utf8');
const source=html.slice(html.indexOf('<script>')+8,html.lastIndexOf('</script>'));
new vm.Script(source);
const code=source.slice(0,source.indexOf('/* ---------------- Init ---------------- */'));
let passed=0;
function test(name,fn){
 const data=new Map();
 const ctx=vm.createContext({console,URL,Date,JSON,Math,Set,Map,assert,setTimeout(){},clearTimeout(){},navigator:{},confirm:()=>true,
  localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),key:i=>[...data.keys()][i],get length(){return data.size;}},window:{addEventListener(){}},document:{addEventListener(){},querySelectorAll(){return [];},querySelector(){return null;}}});
 vm.runInContext(code,ctx);
 vm.runInContext(`state.applications=[{id:'role-test',company:'Test Co',role:'Analyst',stage:'research',market:'Sydney / Melbourne',notes:'',log:[]}];state.contacts=[];render=()=>{};renderStorageNotice=()=>{};toast=()=>{};markDirty=()=>true;`,ctx);
 const run=s=>vm.runInContext(s,ctx);fn(run);console.log('PASS',name);passed++;
}
test('blank and invalid fields do not create contacts',run=>run(`assert.equal(commitContactValues('role-test','',{name:' '}).ok,false);assert.equal(commitContactValues('role-test','',{name:'Jo',email:'not-an-address'}).ok,false);assert.equal(commitContactValues('role-test','',{name:'Jo',linkedin:'javascript:alert(1)'}).ok,false);assert.equal(commitContactValues('role-test','',{name:'Jo',nextFollowUp:'2026-02-30'}).ok,false);assert.equal(state.contacts.length,0);`));
test('new contact defaults unknown and identified with no invented contact details',run=>run(`const result=commitContactValues('role-test','',{name:'Jamie',notes:'Team unconfirmed'});assert(result.ok);const c=state.contacts[0];assert.equal(c.route,'Unknown / to confirm');assert.equal(c.status,'identified');assert.equal(c.email,'');assert.equal(c.notes,'Team unconfirmed');assert.equal(c.log.length,0);`));
test('duplicate names and emails are blocked within the same role',run=>run(`assert(commitContactValues('role-test','',{name:'Jamie',email:'jamie@example.com'}).ok);assert(!commitContactValues('role-test','',{name:' JAMIE ',email:''}).ok);assert(!commitContactValues('role-test','',{name:'Different name',email:'JAMIE@example.com'}).ok);assert.equal(state.contacts.length,1);`));
test('inline edit preserves links, logs and extra provenance',run=>run(`const result=commitContactValues('role-test','',{name:'Jamie',linkedin:'https://example.com/profile',email:'jamie@example.com'});const c=state.contacts[0];c.source='Firsthand';c.log=[{date:'2026-09-01',kind:'sent',text:'Original'}];assert(commitContactValues('role-test',result.id,{...c,title:'BA, to confirm',nextFollowUp:'2026-09-15'}).ok);assert.equal(c.source,'Firsthand');assert.equal(c.log.length,1);assert.equal(c.linkedin,'https://example.com/profile');assert.equal(c.title,'BA, to confirm');`));
test('sent/reply events suggest appropriate progress without regressing later status',run=>run(`const result=commitContactValues('role-test','',{name:'Jamie'}),c=state.contacts[0];assert(commitContactActivity(result.id,{date:todayISO(),kind:'sent',channel:'Email',text:'Actually sent'}).ok);assert.equal(c.status,'reached_out');assert(commitContactActivity(result.id,{date:todayISO(),kind:'received',channel:'Email',text:'Reply received'}).ok);assert.equal(c.status,'replied');c.status='call_booked';commitContactActivity(result.id,{date:todayISO(),kind:'sent',channel:'Email',text:'Sent a time'});assert.equal(c.status,'call_booked');assert.equal(c.log.length,3);`));
test('notes do not imply sent activity and backdated activity does not regress last contact',run=>run(`const result=commitContactValues('role-test','',{name:'Jamie'}),c=state.contacts[0];commitContactActivity(result.id,{date:todayISO(),kind:'note',channel:'Email',text:'Draft only'});assert.equal(c.lastTouch,'');assert.equal(c.status,'identified');commitContactActivity(result.id,{date:todayISO(),kind:'sent',channel:'Email',text:'Sent'});commitContactActivity(result.id,{date:'2020-01-01',kind:'received',channel:'Email',text:'Earlier historical event'});assert.equal(c.lastTouch,todayISO());`));
test('future events and empty activity are rejected; explicit progress override is allowed',run=>run(`const result=commitContactValues('role-test','',{name:'Jamie'}),c=state.contacts[0];assert(!commitContactActivity(result.id,{date:'2999-01-01',kind:'sent',channel:'Email',text:'Future'}).ok);assert(!commitContactActivity(result.id,{date:todayISO(),kind:'sent',channel:'Email',text:' '}).ok);assert.equal(c.log.length,0);assert(commitContactActivity(result.id,{date:todayISO(),kind:'received',channel:'Email',text:'Declined',status:'dormant'}).ok);assert.equal(c.status,'dormant');`));
test('storage failure reports pending data; retrying contact does not duplicate it',run=>run(`markDirty=()=>false;const first=commitContactValues('role-test','',{name:'Jamie'});assert.equal(first.ok,false);assert(first.id);assert.equal(state.contacts.length,1);markDirty=()=>true;assert(commitContactValues('role-test',first.id,{name:'Jamie'}).ok);assert.equal(state.contacts.length,1);markDirty=()=>false;const result=commitContactActivity(first.id,{date:todayISO(),kind:'sent',channel:'Email',text:'Pending'});assert.equal(result.ok,false);assert.equal(result.pending,true);assert.equal(state.contacts[0].log.length,1);`));
test('table encodes untrusted content and exposes follow-up plus inline controls',run=>run(`const result=commitContactValues('role-test','',{name:'<img src=x>',notes:'<script>bad</script>',nextFollowUp:'2026-09-15'});const rendered=peopleTableHTML(appById('role-test'));assert(!rendered.includes('<img src=x>'));assert(rendered.includes('&lt;img'));assert(rendered.includes('15 Sep'));assert(rendered.includes('Log activity'));assert(rendered.includes('+ Add contact'));contactEditor={appId:'role-test',id:'',kind:'person',values:{},error:'',dirty:false};const form=peopleTableHTML(appById('role-test'));assert(form.includes('data-contact-editor'));assert(form.includes('Unknown / to confirm'));assert(form.includes('Cancel'));`));
test('role notepad preserves legacy checklist source without generating copied tasks',run=>run(`const original='Context with uncertainty.\\n- [ ] Ask about the team\\n- bullet';assert(updateRoleNotepad('role-test',original));assert.equal(appById('role-test').notes,original);assert.equal(JSON.parse(JSON.stringify(state)).applications[0].notes,original);assert(roleNotepadHTML(appById('role-test')).includes('data-role-notepad'));assert(!roleNotepadHTML(appById('role-test')).includes('data-role-note-check'));`));
console.log(`${passed} contact checks passed`);
