/* Isolated tests of the canonical standalone app. No browser profile or user storage is read. */
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const html = fs.readFileSync(path.join(__dirname, '..', 'app.html'), 'utf8');
const source = html.slice(html.indexOf('<script>') + 8, html.lastIndexOf('</script>'));
new vm.Script(source); // Include init/accessibility syntax in this check.
const code = source.slice(0, source.indexOf('/* ---------------- Init ---------------- */'));
let passed = 0;
const failures = [];
function harness() {
  const data = new Map(), handlers = {}, messages = [];
  let failWrites = false;
  const localStorage = {getItem: key => data.get(key) ?? null, setItem(key, value) {if (failWrites) throw Error('QuotaExceededError'); data.set(key, String(value));}, key: i => [...data.keys()][i], get length() {return data.size;}};
  const ctx = vm.createContext({console, assert, URL, Set, Map, Date, JSON, Math, localStorage,
    window: {addEventListener() {}}, document: {addEventListener(name, fn, capture) {(handlers[name] ||= []).push({fn,capture});}, querySelectorAll() {return [];}, querySelector() {return null;}},
    navigator: {}, confirm: () => true, setTimeout() {}, clearTimeout() {}, messages,
  });
  vm.runInContext(code, ctx);
  vm.runInContext(`render=()=>{};renderStorageNotice=()=>{};closeModal=()=>{};toast=message=>messages.push(message);toastUndo=(message,fn)=>{undoFn=fn;messages.push(message);};openModal=(html,handler)=>{globalThis.formHTML=html;globalThis.submitForm=handler;};resetEvidenceBaseline();`, ctx);
  return {run: script => vm.runInContext(script, ctx), data, ctx, messages, failWrites: value => {failWrites = value;}, click(action,id) {
    const target = {dataset:{action,id}, tagName:'BUTTON'};
    const event = {target:{closest:()=>target},preventDefault(){},stopImmediatePropagation(){this.stopped=true;}};
    for(const h of (handlers.click||[]).sort((a,b)=>Number(!!b.capture)-Number(!!a.capture))) {h.fn(event);if(event.stopped)break;}
  }};
}
function test(name, fn) {try {fn(harness());passed++;console.log('PASS',name);} catch(error) {failures.push({name,error});console.error('FAIL',name, error.message);}}
test('seed and wrapper/raw export schemas',h=>h.run(`validateState(state);assert(readBackup(exportJSON()).resume.master);assert(readBackup(JSON.stringify(state)).resume.master);`));
test('save, reload and previous-save recovery',h=>h.run(`assert(saveLocal(state,false));const original=storageRaw;state.applications[0].notes='Saved note';assert(saveLocal(state,false));assert.equal(localStorage.getItem(STORAGE_BACKUP),original);state.applications=[];loadLocal();assert.equal(state.applications[0].notes,'Saved note');restoreBackup();assert.equal(localStorage.getItem(STORAGE_BACKUP)!==original,true);assert.notEqual(state.applications[0].notes,'Saved note');`));
test('quota failure preserves persisted state and pending edit',h=>{h.run(`assert(saveLocal(state,false));globalThis.previous=storageRaw;state.applications[0].notes='pending';`);h.failWrites(true);h.run(`assert.equal(markDirty(),false);assert.equal(localStorage.getItem(STORAGE_KEY),previous);assert.equal(state.applications[0].notes,'pending');assert.match(storageError,/not saved/);assert.match(exportJSON(),/pending/);`);});
test('cross-tab write refuses replacement',h=>h.run(`assert(saveLocal(state,false));localStorage.setItem(STORAGE_KEY,'other-tab');state.applications[0].notes='pending';assert(!saveLocal(state,false));assert.equal(localStorage.getItem(STORAGE_KEY),'other-tab');assert.match(storageError,/Another tab/);`));
test('malformed saved data remains untouched until explicit recovery',h=>h.run(`assert(saveLocal(state,false));localStorage.setItem(STORAGE_BACKUP,storageRaw);localStorage.setItem(STORAGE_KEY,'broken JSON');loadLocal();assert(storageBlocked);assert(!saveLocal(state,false));assert.equal(localStorage.getItem(STORAGE_KEY),'broken JSON');restoreBackup();assert(!storageBlocked);assert([...Array(localStorage.length)].map((_,i)=>localStorage.key(i)).some(k=>k.startsWith(STORAGE_KEY+'.recovery.')));`));
test('malformed import does not mutate workspace or storage',h=>h.run(`assert(saveLocal(state,false));const before=storageRaw, original=JSON.stringify(state);const bad=JSON.parse(JSON.stringify(state));bad.resume.master.roles='bad';assert(!doImport(JSON.stringify(bad),true));assert.equal(storageRaw,before);assert.equal(JSON.stringify(state),original);`));
test('unknown version and duplicate IDs rejected',h=>h.run(`const bad=JSON.parse(JSON.stringify(state));bad.meta.version=77;assert.throws(()=>validateState(bad));bad.meta.version=1;bad.applications.push({...bad.applications[0]});assert.throws(()=>validateState(bad));`));
test('import retains workflow extensions and resets evidence baseline',h=>h.run(`const imported=JSON.parse(JSON.stringify(state));imported.applications[0].fullAd='Exact ad';imported.applications[0].potentialValue='Inference';imported.resume.master.source='Firsthand note';imported.resume.master.revision='test-revision';assert(doImport(JSON.stringify(imported),true));const count=state.resume.history.length;markDirty();assert.equal(state.resume.history.length,count);assert.equal(state.applications[0].fullAd,'Exact ad');assert.equal(state.resume.master.source,'Firsthand note');`));
test('archive preserves contacts, tasks, documents and reload recovery',h=>{h.run(`globalThis.roleId=state.applications[0].id;globalThis.contactCount=state.contacts.length;globalThis.taskCount=state.tasks.length;`);h.click('del-app',h.ctx.roleId);h.run(`assert(appById(roleId).archivedAt);assert.equal(state.contacts.length,contactCount);assert.equal(state.tasks.length,taskCount);assert(!isActive(appById(roleId)));loadLocal();assert(appById(roleId).archivedAt);roleFilters.stage='archived';assert(filteredApps().some(a=>a.id===roleId));`);h.click('restore-app',h.ctx.roleId);h.run(`assert(!appById(roleId).archivedAt);`);});
test('master edit archives raw previous master and preserves submitted text',h=>h.run(`const m=state.resume.master;const variant={id:'test-variant',name:'Test draft',appId:state.applications[0].id,headline:'Analyst',summaryId:m.summaries[0].id,picks:{},achievementPicks:{},skillPicks:{},masterRevision:m.revision};m.roles[0].bullets.forEach(b=>variant.picks[b.id]=true);variant.submittedSnapshot={text:'Exact already submitted text',date:'2026-08-03',masterRevision:m.revision};state.resume.variants.push(variant);resetEvidenceBaseline();const old=JSON.stringify(m);m.roles[0].bullets[0].text='New firsthand correction';markDirty();assert.equal(JSON.stringify(state.resume.history.at(-1).master),old);assert.equal(variant.submittedSnapshot.text,'Exact already submitted text');resumeTab=variant.id;assert.equal(resumeText(),'Exact already submitted text');variant.submittedSnapshot.text='Attempted rewrite';markDirty();assert.equal(variant.submittedSnapshot.text,'Exact already submitted text');loadLocal();assert.equal(state.resume.variants[0].submittedSnapshot.text,'Exact already submitted text');`));
test('active draft history captures prior rendered text after master edit',h=>h.run(`const m=state.resume.master;const v={id:'active-test',name:'Active',appId:'',summaryId:m.summaries[0].id,picks:{},achievementPicks:{},skillPicks:{},masterRevision:m.revision};state.resume.variants.push(v);resetEvidenceBaseline();const before=resumeTextFor(m,v);m.summaries[0].text='New verified summary';markDirty();assert.equal(v.history.at(-1).text,before);assert.notEqual(v.masterRevision,m.revision);`));
test('legitimate variant, note, contact log and task fields validate',h=>h.run(`state.tasks.push({id:'task-test',title:'Follow through',due:'',done:false,linkedType:'application',linkedId:state.applications[0].id});state.contacts[0].log.push({date:'2026-09-08',channel:'Email',note:'Recorded after sending'});state.resume.variants.push({id:'variant-test',name:'Networking',appId:'',headline:'',summaryId:'',notes:'',createdAt:'2026-09-08',updatedAt:'2026-09-08',picks:{},achievementPicks:{},skillPicks:{},masterRevision:''});assert(saveLocal(state,false));`));

test('missing required resume header text rejected before import',h=>h.run(`const bad=JSON.parse(JSON.stringify(state));delete bad.resume.master.header.name;assert.throws(()=>validateState(bad));`));
test('malformed master history rejected before import',h=>h.run(`const bad=JSON.parse(JSON.stringify(state));bad.resume.history=[{savedAt:'2026-09-08',master:{}}];assert.throws(()=>validateState(bad));`));
test('role metadata edit preserves source material fields',h=>h.run(`const a=state.applications[0];a.fullAd='Exact original job ad';a.description='Company context';a.potentialValue='Possible contribution';a.aiPolicy='Check posting';appForm(a.id);const keys=[...formHTML.matchAll(/name="([^"]+)"/g)].map(x=>x[1]);const values=Object.fromEntries(keys.map(k=>[k,a[k]||'']));submitForm({get:k=>values[k]??null});assert.equal(a.fullAd,'Exact original job ad');assert.equal(a.description,'Company context');assert.equal(a.potentialValue,'Possible contribution');assert.equal(a.aiPolicy,'Check posting');`));
test('record submitted snapshot uses explicit recorded date and does not submit a role',h=>h.run(`const m=state.resume.master;const v={id:'record-test',name:'Record',appId:state.applications[0].id,summaryId:'',picks:{},achievementPicks:{},skillPicks:{},masterRevision:m.revision};state.resume.variants.push(v);resetEvidenceBaseline();const a=appById(v.appId),stage=a.stage,date=a.dateApplied;recordSubmitted(v.id);assert(submitForm);submitForm({get:k=>k==='date'?'2026-09-01':'on'});assert.equal(v.submittedSnapshot.date,'2026-09-01');assert.equal(a.stage,stage);assert.equal(a.dateApplied,date);assert(saveLocal(state,false));`));


test('submitted variant deletion action is blocked',h=>{h.run(`const v={id:'delete-locked',name:'Locked',appId:'',summaryId:'',picks:{},achievementPicks:{},skillPicks:{},submittedSnapshot:{text:'Sent text',date:'2026-08-03',masterRevision:''}};state.resume.variants.push(v);resetEvidenceBaseline();`);h.click('res-del-variant','delete-locked');h.run(`assert(variantById('delete-locked'));`);});
test('submission recording does not claim success after storage failure',h=>{h.run(`const v={id:'quota-record',name:'Record',appId:'',summaryId:'',picks:{},achievementPicks:{},skillPicks:{},masterRevision:''};state.resume.variants.push(v);resetEvidenceBaseline();recordSubmitted(v.id);`);h.failWrites(true);h.run(`submitForm({get:k=>k==='date'?'2026-09-01':'on'});assert(storageError);assert(!messages.at(-1).includes('Submitted text preserved'));`);});

test('duplicate opportunity rejected without losing original',h=>h.run(`const original=state.applications[0];const count=state.applications.length;appForm();submitForm({get:k=>k==='company'?' '+original.company.toLowerCase()+' ':k==='role'?original.role.toUpperCase():k==='location'?original.location:''});assert.equal(state.applications.length,count);assert(messages.at(-1).includes('already recorded'));`));
test('blank contact name and duplicate contact rejected',h=>h.run(`const c=state.contacts[0],n=state.contacts.length;assert(!commitContactValues(c.appId,'',{name:' '}).ok);assert.equal(state.contacts.length,n);assert(!commitContactValues(c.appId,'',{name:c.name.toUpperCase(),email:c.email||''}).ok);assert.equal(state.contacts.length,n);`));
test('status changes do not invent submission dates',h=>h.run(`const a=state.applications.find(x=>x.stage==='research');assert(!a.dateApplied);commitCell(a.id,'stage','applied');assert(!a.dateApplied);assert.equal(a.stage,'applied');`));
test('draft-only activity does not imply a sent message or last contact',h=>h.run(`const c=state.contacts.find(x=>!x.lastTouch);const a=appById(c.appId);assert(commitContactActivity(c.id,{date:todayISO(),kind:'note',channel:'Email',status:'identified',text:'Draft only'}).ok);assert(!c.lastTouch);assert(!readiness(a).sent);`));
test('drawer typing saves without redraw or focus loss',h=>h.run(`const a=state.applications[0];let redraws=0;render=()=>redraws++;commitDrawer({dataset:{id:a.id,dcell:'draft'},value:'Persistent draft'});assert.equal(redraws,0);assert.equal(readBackup(storageRaw).applications[0].draft,'Persistent draft');`));

console.log(`\n${passed} passed; ${failures.length} failed`);
if(failures.length){for(const failure of failures)console.error('\n'+failure.name+'\n'+failure.error.stack);process.exitCode=1;}
